### ISSUE TITLE
Data split and rendering of ABC dataset

### ISSUE THREAD

**Issue by xianyongqin** [devlearning-gt/3DShapeGen#10]
Where can I find the data split and rendering meta data of ABC dataset?

**Comment by ThibaultGROUEIX** [comment]
Hi,

I would also be interested in the release of the ABC renderings and metadata but I imagine it must be huge.

Kind regards,
Thibault

**Comment by sstojanov** [comment]
Hi xianyongqin and Thibault, 

Our apologies for the delay in this response. Here is a [link](https://www.dropbox.com/s/d4zrpqgvkdpktx0/ABC_30K_data.tar?dl=0) to a tarball of the ABC renders, SDFs and data split. 

Best,
Stefan

**Comment by walsvid** [comment]
Hi @sstojanov ,  thanks for your work. Does this tarball contain already rendered images (such as rgb depth, etc.)?

**Comment by ewrfcas** [comment]
@sstojanov Hi, I am using the ABC_30K_data. While the parameter "resolution" in https://github.com/rehg-lab/3DShapeGen/blob/master/Rendering/ABC/data_generation_parameters.json is 224, the image sizes of rendered images of ABC_30k_data are all 256. It is really strange.

**Comment by sstojanov** [comment]
Hi ewrfcas,

There was some refactoring and cleaning up that we did to release the rendering code, which is most likely when this got swapped from 256 to 224 as this is the size we use for training. Please note that you can always resize the images down to 224x224 or to any other size that suits your requirements.
