### ISSUE TITLE
Image Only Pre-trained Network

### ISSUE THREAD

**Issue by marissachanlatte** [devlearning-gt/3DShapeGen#13]
Hi, 

Thank you for this work. I am interested in using the image only version as a baseline. Before I try training it myself, I was wondering if you happened to have the pre-trained model (image only, 3DOF, VC) hanging around somewhere. It would be very much appreciated!

Thank you,
Marissa

**Comment by ngailapdi** [comment]
Hi Marissa,

Thank you so much for your interest in our work. We have updated the README to include the path to the image only, 3DOF VC trained on LRBg data (first row of table 4 in the paper). We also include the link to download this model [here](https://www.dropbox.com/s/6yhmbwa6stcj1hx/best_model_img_3DOF.pth.tar). Please feel free to let us know if you have any other questions.
