### ISSUE TITLE
Cannot access to pretrained model

### ISSUE THREAD

**Issue by bezbahen0** [devlearning-gt/3DShapeGen#15]
Hi, thanks for your release. I tried to get 2-DOF_VC_with predicted_Depth+Normals by their [link](https://www.dropbox.com/s/x8drovd6qy5tbko/best_model_pred_dn_2DOF.pth.tar) when I found on READEME.md, but I don't have access. Can you help me with this?

**Comment by ngailapdi** [comment]
Hi @bezbahen0,

Thank you for your interest in our work and for bringing up this issue. We have fixed the permission and you should be able to download the pretrained model now. Please do not hesitate to let us know if you have any other questions.
