### ISSUE TITLE
Enable link sharing for data download

### ISSUE THREAD

**Issue by nicolaihaeni** [devlearning-gt/3DShapeGen#16]
Hi

I was wondering if you could enable link sharing so that the data can be downloaded from a Linux console with wget?

Thank you

**Comment by sstojanov** [comment]
Hi, 

Thank you for your interest in our project. You can download the data using wget by modifying the URLs as follows:

```
https://www.dropbox.com/s/yw03ohg04834vvv/ShapeNet55_3DOF-VC_LRBg.tar
```
to
```
https://dl.dropbox.com/s/yw03ohg04834vvv/ShapeNet55_3DOF-VC_LRBg.tar
```

This would allow you to do `wget https://dl.dropbox.com/s/yw03ohg04834vvv/ShapeNet55_3DOF-VC_LRBg.tar` directly from a linux console.

Please let us know if you have further questions.
Stefan
