### ISSUE TITLE
General Information

### ISSUE THREAD

**Issue by janbechtold** [devlearning-gt/3DShapeGen#2]
Hi again,

I have some general questions about the repo:

- How many GPU's, GPU memory and RAM do you use to train the network?
    - I get a CUDAout of memory error for 2 GPU's with 12GB each. 
    - The network is not so big, so I wonder why this needs so much memory
    - I can only train a model on a single datapoint with single GPU (DataParallel set to `device_ids=[0]`)

- In your paper the NW architecture contains a U-ResNet that predicts depth, normals and silhouette from a RGB image. Where can I find this in your repo? The SDFNet/model.py only contains encoder and 3D decoder.
    - Ok, I think I found this in `GenRe-ShapeHD/networks/`

- Why do you need 2 different marching cubes algorithms, i.e. libmcubes for occupancy representation and the marching cubes in SDFNet/isosurface?

Best regards, Jan

**Comment by ngailapdi** [comment]
Hi Jan,
Thanks for your questions. Please see the responses below.
1) We train our network with batch size 128 on 2 GPU's. Each should consume around 8-9GB. I'm not sure if you get CUDA out of mem error during training or validation. You might want to reduce the batch size of validation if it happens during validation.
2) Yes the 2.5D estimation network should be in `GenRe-ShapeHD/networks/`
3) Generally speaking we don't need 2 marching cube libraries. The one we are using is `SDFNet/isosurface`. The other package consists of multiple other libraries such as KDTree for computing Chamfer distance along with the `libmcubes` so we just included everything.

**Comment by ngailapdi** [comment]
Hi Jan,

Just a follow up to see if everything works well for you. If it does should we close this issue?

Thanks

**Comment by janbechtold** [comment]
Yes we can close this issue, thanks for your comments.
