### ISSUE TITLE
Data link broken 

### ISSUE THREAD

**Issue by jing-IG** [devlearning-gt/3DShapeGen#3]
Thanks for sharing the code and data. 

The SDFNet README listed some data. I got a "permission denied" message when accessing "3-DOF VC D+N Pred" at this link:
`https://www.dropbox.com/s/qz227pr2vbrzu9l/ShapeNet55_HVC_LR_PRED.tar`

Other data links seem to work fine. 

BTW, is "3-DOF VC D+N Pred" the data output from the Stage 1 (2D -> 2.5D) network after processing the ground truth data in the link "3-DOF viewpoint LRBg ShapeNetCore.v2 renders"?

**Comment by sstojanov** [comment]
Hi, thank you for your interest in the project and for bringing this up. The link should be fixed now.

Yes the "3-DOF VC D+N PRED" is the output from stage 1 as you described.
