### ISSUE TITLE
Pretrained SDFNet model for Table 3

### ISSUE THREAD

**Issue by xianyongqin** [devlearning-gt/3DShapeGen#6]
Thank you very much for releasing the nice codes. I would like to reproduce your results reported in Table 3 in your arxiv paper. Is it possible to release the pretrained model (SDFNet) and predicted depth and normal used for reproducing Table 3?  Thank you very much!

**Comment by ngailapdi** [comment]
Hi, the link to the pretrained model for 2DOF-VC has been updated in the README file, also attached [here](https://www.dropbox.com/s/x8drovd6qy5tbko/best_model_pred_dn_2DOF.pth.tar)

**Comment by ngailapdi** [comment]
The following [link](https://www.dropbox.com/sh/90k1q33yqjif3at/AADeKnHd_Dm9SeviDGNhoixPa) is the predicted depth and normal maps.

**Comment by ngailapdi** [comment]
Hi, the link to the predicted data has been updated in the README file, also attached [here](https://www.dropbox.com/s/cvsv08j6iv6b8n3/ShapeNet55_2DOF_VC_PRED_SEEN.tar) (for seen data) and [here](
https://www.dropbox.com/s/cwieg8qb8od8coo/ShapeNet55_2DOF_VC_PRED_UNSEEN.tar) (for unseen data). Please feel free to reopen this issue if you have further questions.
