### ISSUE TITLE
Rendering script fails on Mac

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [devlearning-gt/3DShapeGen#9]
Hi,

Thanks for your great work and for sharing all the code to generate the data. 

I am trying to get the rotation matrix  from the metadata. I've been struggling a bit with this so I tried reusing the rendering script you provide i.e `generate.py` to  render a shapenet object with simple parameters. The script gives several errors on Mac, hence my question :
* did you render shapenet on Linux or Mac?

These errors are for instance :
```shell
  File "utils/render_utils.py", line 66, in make_area_lamp
    nodes = lamp.node_tree.nodes
AttributeError: 'NoneType' object has no attribute 'nodes'
```
This can be solved by setting : 
``` lamp.use_nodes = True``` but there are other errors after this. 

If you have any pointers to go from the metadata files to the rotation matrix, that would be great. I tried inversing the sequence of Euler-angle transformations in `generate.py` but the resulting matrix is not consistent with the renderings so far.
Cheers,
Thibault

**Comment by sstojanov** [comment]
Hi Thibault, 

Thank you for your kind words and interest in our work! I have a few questions:

1. Are you trying to use our scripts with Blender 2.79b specifically? If so, then the scripts should work identically on Mac and on Linux. (more detail: the rendering itself was done on Linux, but we've done some developing/debugging on Mac and had the code work in both cases)
2. When you say rotation matrix, do you mean the the appropriate R, t (and K for projection) that would allow you, for example, to take a surface point cloud from the 3D model being rendered, transform and project it into the image? If this is the case, we have some code internally that builds on this release which allows for that functionality (dumps the camera intrinsic/extrinsic matrices in addition to the images/depths/normals for each frame). Do you think that would be useful for you?

Best,
Stefan

**Comment by ThibaultGROUEIX** [comment]
Hi @sstojanov,

Thanks for your fast reply.
1. Yes i was trying to use your script on Mac with a freshly installed Blender 2.79b from the link you provide. I am not sure why it fails then, but this was mostly done as a way to debug point 2.
2. Yes exactly,  i am trying to write code that takes as input `hard_vc_metadata.txt` and `metadata.txt` and outputs the correct rotation matrix applied to the base shapenet model in a right-handed coordinate system (z forward, Y up, x left). I think your code could be very useful.

Thanks again!

**Comment by sstojanov** [comment]
Unfortunately I'm not sure why there are issues with the MacOS. For me it worked with 10.14.06 Mojave and previous versions. What version of MacOS are you using? 

Regarding extracting the camera information, following is more detail. We are working on integrating this into the release, but the current answer is in terms of github gists.

Here are links to gists for an updated `generate.py` ([link](https://gist.github.com/sstojanov/e02afe9a53677d873e866b212cb0f464)) and functions that need to be added to `render_utils.py` ([link](https://gist.github.com/sstojanov/c74963cdfaa508d6f31780879ceb0531)) for the camera rotation and calibration matrices to be output. 

You can test these functions by doing the following:

1. Take an `.obj` from ShapeNet
2. Extract a point cloud using [trimesh](https://trimsh.org/trimesh.sample.html) and save it as  `pointcloud3.npz`
3. Convert that point cloud into the same orientation as the mesh in Blender using the [following code](https://gist.github.com/sstojanov/e81041e79a39cf5ff0e96f1427a5f0d5).
4. Project the point cloud points using the [following code](https://gist.github.com/sstojanov/0feaea3cfb66231dd3d76bd100e0f61f)

Following are some files that can help unit test/determine whether things are working properly

1. The following contains an example output rendering with the camera information output as `cam.npz`
[02691156.zip](https://github.com/rehg-lab/3DShapeGen/files/6954981/02691156.zip)
2. Point cloud in original `pointcloud3.npz` and `pointcloud3_R.npz` Blender rendering orientation (this is before and after step 3 in the steps above)  [pointclouds.zip](https://github.com/rehg-lab/3DShapeGen/files/6955014/pointclouds.zip)

If everything works correctly, the projected point cloud should correspond to the object in the image like in the example below. The image on the right was obtained following the testing steps 1 through 4 above.
![image](https://user-images.githubusercontent.com/13421307/128719575-53aacc32-c0f2-4cd1-957a-a646995fdb72.png)![image](https://user-images.githubusercontent.com/13421307/128719543-695e3783-d62d-4aa6-be4a-ac7ad57e4853.png)


Please let me know if you have further questions!
Best,
Stefan

**Comment by ThibaultGROUEIX** [comment]
Hi Stefan,
Loads of thanks for the detailed answer. I will go over the script and close the issue as soon as I reach the objective if that’s ok. 
Best
Thibault

**Comment by sstojanov** [comment]
Hi Thibault, have you been able to make any progress on this?

Best,
Stefan

**Comment by marissachanlatte** [comment]
Hi Stefan, 

I've been working with Thibault on this (he's on vacation) and yes, your scripts were very helpful. We were able to get what we needed. 

Thank you! 

Marissa

**Comment by sstojanov** [comment]
Glad to hear it! I'll go ahead and close the issue.
